Update flutter-build.yml

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -230,145 +230,145 @@ jobs:
             ./SignOutput/rustdesk-*.exe
 
   # The fallback for the flutter version, we use Sciter for 32bit Windows.
-  build-for-windows-sciter:
-    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
-    runs-on: ${{ matrix.job.os }}
-    # Temporarily disable this action due to additional test is needed.
-    # if: false
-    strategy:
-      fail-fast: false
-      matrix:
-        job:
-          # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
-          # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
-          - {
-              target: i686-pc-windows-msvc,
-              os: windows-2022,
-              arch: x86,
-              vcpkg-triplet: x86-windows-static,
-            }
-          # - { target: aarch64-pc-windows-msvc, os: windows-2022 }
-    steps:
-      - name: Export GitHub Actions cache environment variables
-        uses: actions/github-script@v6
-        with:
-          script: |
-            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
-            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
+  # build-for-windows-sciter:
+  #   name: ${{ matrix.job.target }} (${{ matrix.job.os }})
+  #   runs-on: ${{ matrix.job.os }}
+  #   # Temporarily disable this action due to additional test is needed.
+  #   # if: false
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       job:
+  #         # - { target: i686-pc-windows-msvc        , os: windows-2022                  }
+  #         # - { target: x86_64-pc-windows-gnu       , os: windows-2022                  }
+  #         - {
+  #             target: i686-pc-windows-msvc,
+  #             os: windows-2022,
+  #             arch: x86,
+  #             vcpkg-triplet: x86-windows-static,
+  #           }
+  #         # - { target: aarch64-pc-windows-msvc, os: windows-2022 }
+  #   steps:
+  #     - name: Export GitHub Actions cache environment variables
+  #       uses: actions/github-script@v6
+  #       with:
+  #         script: |
+  #           core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
+  #           core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
 
-      - name: Checkout source code
-        uses: actions/checkout@v4
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
 
-      - name: Install LLVM and Clang
-        uses: rustdesk-org/install-llvm-action-32bit@master
-        with:
-          version: ${{ env.LLVM_VERSION }}
+  #     - name: Install LLVM and Clang
+  #       uses: rustdesk-org/install-llvm-action-32bit@master
+  #       with:
+  #         version: ${{ env.LLVM_VERSION }}
 
-      - name: Install Rust toolchain
-        uses: dtolnay/rust-toolchain@v1
-        with:
-          toolchain: nightly-2023-10-13-${{ matrix.job.target }} # must use nightly here, because of abi_thiscall feature required
-          targets: ${{ matrix.job.target }}
-          components: "rustfmt"
+  #     - name: Install Rust toolchain
+  #       uses: dtolnay/rust-toolchain@v1
+  #       with:
+  #         toolchain: nightly-2023-10-13-${{ matrix.job.target }} # must use nightly here, because of abi_thiscall feature required
+  #         targets: ${{ matrix.job.target }}
+  #         components: "rustfmt"
 
-      - uses: Swatinem/rust-cache@v2
-        with:
-          prefix-key: ${{ matrix.job.os }}-sciter
+  #     - uses: Swatinem/rust-cache@v2
+  #       with:
+  #         prefix-key: ${{ matrix.job.os }}-sciter
 
-      - name: Setup vcpkg with Github Actions binary cache
-        uses: lukka/run-vcpkg@v11
-        with:
-          vcpkgDirectory: C:\vcpkg
-          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
-          doNotCache: false
+  #     - name: Setup vcpkg with Github Actions binary cache
+  #       uses: lukka/run-vcpkg@v11
+  #       with:
+  #         vcpkgDirectory: C:\vcpkg
+  #         vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
+  #         doNotCache: false
 
-      - name: Install vcpkg dependencies
-        env:
-          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.job.vcpkg-triplet }}
-        run: |
-          if ! $VCPKG_ROOT/vcpkg \
-            install \
-            --triplet ${{ matrix.job.vcpkg-triplet }} \
-            --x-install-root="$VCPKG_ROOT/installed"; then
-            find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
-              echo "$_1:"
-              echo "======"
-              cat "$_1"
-              echo "======"
-              echo ""
-            done
-            exit 1
-          fi
-        shell: bash
+  #     - name: Install vcpkg dependencies
+  #       env:
+  #         VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.job.vcpkg-triplet }}
+  #       run: |
+  #         if ! $VCPKG_ROOT/vcpkg \
+  #           install \
+  #           --triplet ${{ matrix.job.vcpkg-triplet }} \
+  #           --x-install-root="$VCPKG_ROOT/installed"; then
+  #           find "${VCPKG_ROOT}/" -name "*.log" | while read -r _1; do
+  #             echo "$_1:"
+  #             echo "======"
+  #             cat "$_1"
+  #             echo "======"
+  #             echo ""
+  #           done
+  #           exit 1
+  #         fi
+  #       shell: bash
 
-      - name: Build rustdesk
-        id: build
-        shell: bash
-        run: |
-          python3 res/inline-sciter.py
-          # Patch sciter x86
-          sed -i 's/branch = "dyn"/branch = "dyn_x86"/g' ./Cargo.toml
-          cargo build --features inline,vram,hwcodec --release --bins
-          mkdir -p ./Release
-          mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
-          curl -LJ -o ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
-          echo "output_folder=./Release" >> $GITHUB_OUTPUT
-          curl -LJ -o ./usbmmidd_v2.zip https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip
-          unzip usbmmidd_v2.zip
-          # Do not remove x64 files, because the user may run the 32bit version on a 64bit system.
-          # Do not remove ./usbmmidd_v2/deviceinstaller64.exe, as x86 exe cannot install and uninstall drivers when running on x64,
-          # we need the x64 exe to install and uninstall the driver.
-          rm -rf ./usbmmidd_v2/deviceinstaller.exe ./usbmmidd_v2/usbmmidd.bat
-          mv ./usbmmidd_v2 ./Release || true
+  #     - name: Build rustdesk
+  #       id: build
+  #       shell: bash
+  #       run: |
+  #         python3 res/inline-sciter.py
+  #         # Patch sciter x86
+  #         sed -i 's/branch = "dyn"/branch = "dyn_x86"/g' ./Cargo.toml
+  #         cargo build --features inline,vram,hwcodec --release --bins
+  #         mkdir -p ./Release
+  #         mv ./target/release/rustdesk.exe ./Release/rustdesk.exe
+  #         curl -LJ -o ./Release/sciter.dll https://github.com/c-smile/sciter-sdk/raw/master/bin.win/x32/sciter.dll
+  #         echo "output_folder=./Release" >> $GITHUB_OUTPUT
+  #         curl -LJ -o ./usbmmidd_v2.zip https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip
+  #         unzip usbmmidd_v2.zip
+  #         # Do not remove x64 files, because the user may run the 32bit version on a 64bit system.
+  #         # Do not remove ./usbmmidd_v2/deviceinstaller64.exe, as x86 exe cannot install and uninstall drivers when running on x64,
+  #         # we need the x64 exe to install and uninstall the driver.
+  #         rm -rf ./usbmmidd_v2/deviceinstaller.exe ./usbmmidd_v2/usbmmidd.bat
+  #         mv ./usbmmidd_v2 ./Release || true
 
-      - name: find Runner.res
-        # Windows: find Runner.res (compiled from ./flutter/windows/runner/Runner.rc), copy to ./Runner.res
-        # Runner.rc does not contain actual version, but Runner.res does
-        continue-on-error: true
-        shell: bash
-        run: |
-          runner_res=$(find . -name "Runner.res");
-          if [ "$runner_res" == "" ]; then
-            echo "Runner.res: not found";
-          else
-            echo "Runner.res: $runner_res";
-            cp $runner_res ./libs/portable/Runner.res;
-            echo "list ./libs/portable/Runner.res";
-            ls -l ./libs/portable/Runner.res;
-          fi
+  #     - name: find Runner.res
+  #       # Windows: find Runner.res (compiled from ./flutter/windows/runner/Runner.rc), copy to ./Runner.res
+  #       # Runner.rc does not contain actual version, but Runner.res does
+  #       continue-on-error: true
+  #       shell: bash
+  #       run: |
+  #         runner_res=$(find . -name "Runner.res");
+  #         if [ "$runner_res" == "" ]; then
+  #           echo "Runner.res: not found";
+  #         else
+  #           echo "Runner.res: $runner_res";
+  #           cp $runner_res ./libs/portable/Runner.res;
+  #           echo "list ./libs/portable/Runner.res";
+  #           ls -l ./libs/portable/Runner.res;
+  #         fi
 
-      - name: Sign rustdesk files
-        if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
-        shell: bash
-        run: |
-          pip3 install requests argparse
-          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./Release/
+  #     - name: Sign rustdesk files
+  #       if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
+  #       shell: bash
+  #       run: |
+  #         pip3 install requests argparse
+  #         BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./Release/
 
-      - name: Build self-extracted executable
-        shell: bash
-        run: |
-          sed -i '/dpiAware/d' res/manifest.xml
-          pushd ./libs/portable
-          pip3 install -r requirements.txt
-          python3 ./generate.py -f ../../Release/ -o . -e ../../Release/rustdesk.exe
-          popd
-          mkdir -p ./SignOutput
-          mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}-sciter.exe
+  #     - name: Build self-extracted executable
+  #       shell: bash
+  #       run: |
+  #         sed -i '/dpiAware/d' res/manifest.xml
+  #         pushd ./libs/portable
+  #         pip3 install -r requirements.txt
+  #         python3 ./generate.py -f ../../Release/ -o . -e ../../Release/rustdesk.exe
+  #         popd
+  #         mkdir -p ./SignOutput
+  #         mv ./target/release/rustdesk-portable-packer.exe ./SignOutput/rustdesk-${{ env.VERSION }}-${{ matrix.job.arch }}-sciter.exe
 
-      - name: Sign rustdesk self-extracted file
-        if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
-        shell: bash
-        run: |
-          BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./SignOutput/
+  #     - name: Sign rustdesk self-extracted file
+  #       if: env.UPLOAD_ARTIFACT == 'true' && env.SIGN_BASE_URL != ''
+  #       shell: bash
+  #       run: |
+  #         BASE_URL=${{ secrets.SIGN_BASE_URL }} SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }} python3 res/job.py sign_files ./SignOutput/
 
-      - name: Publish Release
-        uses: softprops/action-gh-release@v1
-        if: env.UPLOAD_ARTIFACT == 'true'
-        with:
-          prerelease: true
-          tag_name: ${{ env.TAG_NAME }}
-          files: |
-            ./SignOutput/rustdesk-*.exe
+  #     - name: Publish Release
+  #       uses: softprops/action-gh-release@v1
+  #       if: env.UPLOAD_ARTIFACT == 'true'
+  #       with:
+  #         prerelease: true
+  #         tag_name: ${{ env.TAG_NAME }}
+  #         files: |
+  #           ./SignOutput/rustdesk-*.exe
 
   build-for-macOS-arm64-selfhost:
     # use build-for-macOS instead
